repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        files: &python_files ^(nvfp4_gemm_cute|tests|benchmarks|examples)/.*\.py$
      - id: ruff-format
        files: *python_files
